#!/usr/bin/ansible-playbook -v

---
- name: Configure the irefindex access VM
  hosts: irefaccess
  become: yes
  become_user: root

  vars:
    user: lducazu_gmail_com
    relversion: 19
    irefindexbase: "/home/{{ user }}/irefindex"
    pg_host_addr: "{{ lookup('pipe', 'gcloud sql instances list --format=value\\(ipAddresses[0].ipAddress\\)') }}"
    pg_passwd: "{{ lookup('file', '../secrets/pgpasswd') }}"

  tasks:
  - name: Update system
    apt: update_cache=yes upgrade=safe autoremove=yes

  # Generic packages -- required
  - name: Install required packages
    apt:
      pkg:
      - python3-defusedxml
      - python3-pip
      - wget
      - unzip

  - name: Install or upgrade irefindex python dependencies
    pip:
      name: irdata
      state: latest
    become: no

  # Generic packages -- optional
  - name: Install optional packages
    apt:
      pkg:
      - htop
      - rsync
      - tmux

  - name: Shell convenience config
    copy: src=convenience.sh dest=/etc/profile.d/

  # - name: Mount data disk
  #   mount:
  #     src: /dev/disk/by-id/google-dataext
  #     path: /dataext
  #     fstype: xfs
  #     passno: "2"
  #     state: mounted

  - name: Create data directory
    file:
      path: "/dataext/irdata{{ relversion }}"
      state: directory
      mode: "0755"
      owner: "{{ user }}"
      group: "{{ user }}"

  # PostgreSQL

  - name: Install PostgreSQL client
    apt:
      pkg:
      - postgresql-client

  - name: Configure PostgreSQL client
    template:
      src: bash_profile.j2
      dest: .bash_profile
    become: no

  # irefindex

  - name: Install git
    apt:
      pkg:
      - git

  - name: Deploy irefindex from GitHub
    git:
      repo: "git@github.com:vibbits/irefindex.git"
      dest: "{{ irefindexbase }}"
      accept_hostkey: yes  # Replace with "accept_newhostkey: yes" in ansible >= 2.12
    become: no

  - name: Create logs directory
    file: path="{{ irefindexbase }}/var/log/irdata" state=directory
    become: no

  - name: Create irefindex user home directory
    file:
      path: "/home/irefindex"
      src: "{{ irefindexbase }}"
      state: link
      force: yes

  - name: Install R and packages
    apt:
      pkg:
      - r-base
      - r-cran-domc
      - r-cran-dplyr
      - r-cran-readr

  - name: Copy validation scripts
    copy:
      src: "validation/{{ item }}"
      dest: "/dataext/irdata{{ relversion }}/"
    become: no
    with_items:
      - irefindex_validation_script.R
      - mitab_analysis.R
